# Generated by Django 4.2 on 2023-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronica',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='made_in',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('Germany', 'Germany'), ('China', 'China'), ('Japan', 'Japan')], max_length=50, null=True),
        ),
    ]
